/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as AppImport } from './pages/_app'

// Create Virtual Routes

const SigninLazyImport = createFileRoute('/signin')()
const AppUploadLazyImport = createFileRoute('/_app/upload')()
const AppSettingsLazyImport = createFileRoute('/_app/settings')()
const AppReaderLazyImport = createFileRoute('/_app/reader')()
const AppLibraryLazyImport = createFileRoute('/_app/library')()

// Create/Update Routes

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/signin.lazy').then((d) => d.Route))

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppUploadLazyRoute = AppUploadLazyImport.update({
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./pages/_app/upload.lazy').then((d) => d.Route))

const AppSettingsLazyRoute = AppSettingsLazyImport.update({
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./pages/_app/settings.lazy').then((d) => d.Route))

const AppReaderLazyRoute = AppReaderLazyImport.update({
  path: '/reader',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./pages/_app/reader.lazy').then((d) => d.Route))

const AppLibraryLazyRoute = AppLibraryLazyImport.update({
  path: '/library',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./pages/_app/library.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/reader': {
      id: '/_app/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof AppReaderLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadLazyImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppLibraryLazyRoute: typeof AppLibraryLazyRoute
  AppReaderLazyRoute: typeof AppReaderLazyRoute
  AppSettingsLazyRoute: typeof AppSettingsLazyRoute
  AppUploadLazyRoute: typeof AppUploadLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLibraryLazyRoute: AppLibraryLazyRoute,
  AppReaderLazyRoute: AppReaderLazyRoute,
  AppSettingsLazyRoute: AppSettingsLazyRoute,
  AppUploadLazyRoute: AppUploadLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/library': typeof AppLibraryLazyRoute
  '/reader': typeof AppReaderLazyRoute
  '/settings': typeof AppSettingsLazyRoute
  '/upload': typeof AppUploadLazyRoute
}

export interface FileRoutesByTo {
  '': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/library': typeof AppLibraryLazyRoute
  '/reader': typeof AppReaderLazyRoute
  '/settings': typeof AppSettingsLazyRoute
  '/upload': typeof AppUploadLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/_app/library': typeof AppLibraryLazyRoute
  '/_app/reader': typeof AppReaderLazyRoute
  '/_app/settings': typeof AppSettingsLazyRoute
  '/_app/upload': typeof AppUploadLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/signin' | '/library' | '/reader' | '/settings' | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/signin' | '/library' | '/reader' | '/settings' | '/upload'
  id:
    | '__root__'
    | '/_app'
    | '/signin'
    | '/_app/library'
    | '/_app/reader'
    | '/_app/settings'
    | '/_app/upload'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SigninLazyRoute: typeof SigninLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SigninLazyRoute: SigninLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/signin"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/library",
        "/_app/reader",
        "/_app/settings",
        "/_app/upload"
      ]
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/_app/library": {
      "filePath": "_app/library.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/reader": {
      "filePath": "_app/reader.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/settings": {
      "filePath": "_app/settings.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/upload": {
      "filePath": "_app/upload.lazy.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
