/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppRouteImport } from './pages/_app'
import { Route as AppReaderBookIdRouteImport } from './pages/_app/reader.$bookId'

const SigninLazyRouteImport = createFileRoute('/signin')()
const AppUploadLazyRouteImport = createFileRoute('/_app/upload')()
const AppSettingsLazyRouteImport = createFileRoute('/_app/settings')()
const AppLibraryLazyRouteImport = createFileRoute('/_app/library')()

const SigninLazyRoute = SigninLazyRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/signin.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadLazyRoute = AppUploadLazyRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./pages/_app/upload.lazy').then((d) => d.Route))
const AppSettingsLazyRoute = AppSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./pages/_app/settings.lazy').then((d) => d.Route))
const AppLibraryLazyRoute = AppLibraryLazyRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./pages/_app/library.lazy').then((d) => d.Route))
const AppReaderBookIdRoute = AppReaderBookIdRouteImport.update({
  id: '/reader/$bookId',
  path: '/reader/$bookId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof SigninLazyRoute
  '/library': typeof AppLibraryLazyRoute
  '/settings': typeof AppSettingsLazyRoute
  '/upload': typeof AppUploadLazyRoute
  '/reader/$bookId': typeof AppReaderBookIdRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninLazyRoute
  '/library': typeof AppLibraryLazyRoute
  '/settings': typeof AppSettingsLazyRoute
  '/upload': typeof AppUploadLazyRoute
  '/reader/$bookId': typeof AppReaderBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/_app/library': typeof AppLibraryLazyRoute
  '/_app/settings': typeof AppSettingsLazyRoute
  '/_app/upload': typeof AppUploadLazyRoute
  '/_app/reader/$bookId': typeof AppReaderBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signin'
    | '/library'
    | '/settings'
    | '/upload'
    | '/reader/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to: '/signin' | '/library' | '/settings' | '/upload' | '/reader/$bookId'
  id:
    | '__root__'
    | '/_app'
    | '/signin'
    | '/_app/library'
    | '/_app/settings'
    | '/_app/upload'
    | '/_app/reader/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SigninLazyRoute: typeof SigninLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reader/$bookId': {
      id: '/_app/reader/$bookId'
      path: '/reader/$bookId'
      fullPath: '/reader/$bookId'
      preLoaderRoute: typeof AppReaderBookIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLibraryLazyRoute: typeof AppLibraryLazyRoute
  AppSettingsLazyRoute: typeof AppSettingsLazyRoute
  AppUploadLazyRoute: typeof AppUploadLazyRoute
  AppReaderBookIdRoute: typeof AppReaderBookIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLibraryLazyRoute: AppLibraryLazyRoute,
  AppSettingsLazyRoute: AppSettingsLazyRoute,
  AppUploadLazyRoute: AppUploadLazyRoute,
  AppReaderBookIdRoute: AppReaderBookIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SigninLazyRoute: SigninLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
